# House price prediction (with TensorBoard)
Predicting house prices in Boston, Massachusetts while logging results for TensorBoard

#### Load dependencies

In [1]:
import numpy as np
from tensorflow.keras.datasets import boston_housing 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout 
from tensorflow.keras.layers import BatchNormalization 
from tensorflow.keras.callbacks import ModelCheckpoint 
from tensorflow.keras.callbacks import TensorBoard # new!  
import os 

#### Load data

In [2]:
(X_train, y_train), (X_valid, y_valid) = boston_housing.load_data()

In [3]:
X_train.shape

(404, 13)

In [4]:
X_valid.shape

(102, 13)

In [5]:
X_train[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [6]:
y_train[0]

15.2

#### Design neural network architecture

In [7]:
model = Sequential()

model.add(Dense(32, input_dim=13, activation='relu'))
model.add(BatchNormalization())

model.add(Dense(16, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))

model.add(Dense(1, activation='linear'))

In [8]:
model.summary()

Model: "sequential"

_________________________________________________________________

Layer (type)                 Output Shape              Param #   


dense (Dense)                (None, 32)                448       

_________________________________________________________________

batch_normalization (BatchNo (None, 32)                128       

_________________________________________________________________

dense_1 (Dense)              (None, 16)                528       

_________________________________________________________________

batch_normalization_1 (Batch (None, 16)                64        

_________________________________________________________________

dropout (Dropout)            (None, 16)                0         

_________________________________________________________________

dense_2 (Dense)              (None, 1)                 17        


Total params: 1,185

Trainable params: 1,089

Non-trainable params: 96

__________________________________

#### Configure Model

In [9]:
model.compile(loss='mean_squared_error', optimizer='adam', )

In [10]:
output_dir = 'model_output/'

In [11]:
run_name = 'regression_baseline'
output_path = output_dir + run_name

In [12]:
if not os.path.exists(output_path):
    os.makedirs(output_path)

In [13]:
modelcheckpoint = ModelCheckpoint(output_path + '/weights.{epoch:02d}.hdf5', # decimal integers
                                  save_weights_only=True) # otherwise full model is saved

In [14]:
tensorboard = TensorBoard(log_dir='logs/' + run_name)

#### Train!

In [15]:
model.fit(X_train, y_train, 
          batch_size=8, epochs=32, verbose=1, 
          validation_data=(X_valid, y_valid),
          callbacks=[modelcheckpoint, tensorboard]) 

Train on 404 samples, validate on 102 samples

Epoch 1/32

404/404 [==============================] - 1s 2ms/sample - loss: 587.6668 - val_loss: 680.7983

Epoch 2/32

404/404 [==============================] - 0s 323us/sample - loss: 565.8801 - val_loss: 659.5214

Epoch 3/32

404/404 [==============================] - 0s 322us/sample - loss: 548.8434 - val_loss: 631.0423

Epoch 4/32

404/404 [==============================] - 0s 342us/sample - loss: 531.8849 - val_loss: 561.6263

Epoch 5/32

404/404 [==============================] - 0s 317us/sample - loss: 509.8884 - val_loss: 539.1380

Epoch 6/32

404/404 [==============================] - 0s 312us/sample - loss: 486.0127 - val_loss: 499.1526

Epoch 7/32

404/404 [==============================] - 0s 309us/sample - loss: 452.2261 - val_loss: 468.7240

Epoch 8/32

404/404 [==============================] - 0s 295us/sample - loss: 415.7714 - val_loss: 438.4499

Epoch 9/32

404/404 [==============================] - 0s 295us/sample - lo

#### Performing inference

In [20]:
model.load_weights(output_path + '/weights.28.hdf5')

In [21]:
X_valid[42]

array([  9.32909,   0.     ,  18.1    ,   0.     ,   0.713  ,   6.185  ,
        98.7    ,   2.2616 ,  24.     , 666.     ,  20.2    , 396.9    ,
        18.13   ])

In [22]:
y_valid[42]

14.1

In [23]:
model.predict(np.reshape(X_valid[42], [1, 13]))

array([[14.776713]], dtype=float32)